GET http://localhost:3000/produtos

GET http://localhost:3000/produtos/1

POST http://localhost:3000/produtos
Content-Type: application/json

{
    "nome": "Monitor",
    "preco": 800
}

PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
    "nome": "Mouse Gamer",
    "preco": 120
}

DELETE http://localhost:3000/produtos/2
